# fly.toml app configuration file generated for dailyomorimusic on 2023-05-23T23:33:11-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dailyomorimusic"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"
